services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # (Tùy chọn) Script để tự động tạo bảng khi khởi chạy lần đầu
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: